# Generated by Django 6.0 on 2025-12-08 20:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome_fantasia', models.CharField(max_length=60, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('status_assinatura', models.BooleanField(default=True)),
                ('cargo', models.CharField(choices=[('SUPERADMIN', 'Super Admin (Proprietária)'), ('GERENTE', 'Gerente (Cliente Admin)'), ('OPERADOR', 'Operador (Funcionário)')], default='GERENTE', max_length=20)),
                ('empresa_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('localizacao', models.CharField(blank=True, max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pneu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fogo', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(max_length=50, null=True)),
                ('modelo', models.CharField(max_length=50, null=True)),
                ('medida', models.CharField(max_length=50, null=True)),
                ('posicao_veiculo', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('ESTOQUE', 'Em Estoque'), ('EM_USO', 'Rodando no Veículo'), ('MANUTENCAO', 'Em Manutenção'), ('SUCATA', 'Descartado')], default='ESTOQUE', max_length=15)),
                ('km_total_acumulado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sulco_novo_mm', models.DecimalField(decimal_places=1, default=18.0, max_digits=4)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pneus', to=settings.AUTH_USER_MODEL)),
                ('estoque_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estoque')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoPneu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('MONTAGEM', 'Montar no Veículo'), ('DESMONTAGEM', 'Retirar do Veículo'), ('COMPRA', 'Entrada por Compra'), ('DESCARTE', 'Saída para Sucata')], max_length=20)),
                ('origem', models.CharField(blank=True, max_length=50)),
                ('destino', models.CharField(blank=True, max_length=50)),
                ('km_momento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacao', models.TextField(blank=True)),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pneu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pneu')),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(max_length=45)),
                ('data_envio', models.DateField()),
                ('data_retorno', models.DateField(blank=True, null=True)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('km_no_envio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('concluido', models.BooleanField(default=False)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pneu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='core.pneu')),
            ],
        ),
        migrations.CreateModel(
            name='Inspecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inspecao', models.DateTimeField(auto_now_add=True)),
                ('pressao_psi', models.IntegerField()),
                ('sulco_atual_mm', models.DecimalField(decimal_places=1, max_digits=4)),
                ('alerta_critico', models.BooleanField(default=False)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pneu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecoes', to='core.pneu')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=45)),
                ('tipo', models.CharField(choices=[('CAMINHAO', 'Caminhão'), ('CARRETA', 'Carreta'), ('ONIBUS', 'Ônibus')], default='CAMINHAO', max_length=20)),
                ('km_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('eixos', models.IntegerField(default=2)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pneu',
            name='veiculo_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pneus_instalados', to='core.veiculo'),
        ),
    ]
