# Generated by Django 6.0 on 2025-12-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cargo',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin (Proprietária)'), ('GERENTE', 'Gerente (Cliente Admin)'), ('OPERADOR', 'Operador (Funcionário)')], default='SUPERADMIN', max_length=20),
        ),
    ]
